.DEFAULT_GOAL := run-dist

run-dist: 
	./build/install/app/bin/app

comp:
	./gradlew installDist

clean:
	./gradlew clean

build:
	./gradlew clean build

install:
  ./gradlew clean install

.PHONY: build